{{- if eq .Values.type "cronjob" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
    env: {{ .Values.envShort }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Values.appName }}
              image: {{ .Values.image }}/{{ .Values.appName }}:{{ .Values.appVersion }}
              imagePullPolicy: {{ .Values.imagePullPolicy }}
              resources:
                requests:
                  cpu: {{ .Values.resources.requests.cpu }}
                  memory: {{ .Values.resources.requests.memory }}
                limits:
                  memory: {{ .Values.resources.limits.memory }}
              env:
              {{- range $key, $value := .Values.environments }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
              {{- end }}
          restartPolicy: OnFailure
{{- end }}
