{{- if and (eq .Values.type "app") (.Values.ingress.enabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-group
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme}}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.target}}
    alb.ingress.kubernetes.io/security-groups: {{ .Values.ingress.sg }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.healthcheck.path }}
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.group }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificate }}
    alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=true
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http.preserve_host_header.enabled=true
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http.xff_header_processing.mode=preserve
    alb.ingress.kubernetes.io/actions.{{ .Values.appName }}: '{ "Type": "forward", "ForwardConfig": { "TargetGroups": [ { "Weight": 100, "ServiceName": "{{ .Values.appName }}", "ServicePort": "{{ (index .Values.service.ports 0).port }}" } ] } }'
    alb.ingress.kubernetes.io/tags: Owner=ariel.ortmann@strike.sh,Environment={{ .Values.envShort }},Monitoring=ElasticAPM,ContainsUserData=true,UserDataStored=false,Description=InternalALBGroup,Repo=helm-apps
    {{- if ne .Values.ingress.domain "preview.strike.sh" }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.appName }}.{{ .Values.envShort }}.{{ .Values.ingress.domain }}
    {{- else }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.appName }}.{{ .Values.ingress.domain }}
    {{- end }}
  labels:
    app: {{ .Values.appName }}
spec:
  rules:
  {{- if ne .Values.ingress.domain "preview.strike.sh" }}
  - host: {{ .Values.appName }}.{{ .Values.envShort }}.{{ .Values.ingress.domain }}
  {{- else }}
  - host: {{ .Values.appName }}.{{ .Values.ingress.domain }}
  {{- end }}
    http:
      paths:
        # Default path routes to first port (mcp-browser on 3000)
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.appName }}
              port:
                number: {{ (index .Values.service.ports 0).port }}
        # Additional paths for other ports
        {{- if gt (len .Values.service.ports) 1 }}
        {{- range $index, $port := .Values.service.ports }}
        {{- if ne $index 0 }}
        - path: /{{ $port.name }}
          pathType: Prefix
          backend:
            service:
              name: {{ $.Values.appName }}
              port:
                number: {{ $port.port }}
        {{- end }}
        {{- end }}
        {{- end }}
{{- end }}