{{- if and (or (eq .Values.type "app") (eq .Values.type "worker")) (.Values.service.enabled) }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
    env: {{ .Values.envShort }}
    version: {{ .Values.appVersion | quote  }}
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.appPort }}
{{- end }}