{{- if and (or (eq .Values.type "app") (eq .Values.type "worker")) (.Values.hpa.enabled) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.appName }}-pdb
  namespace: {{ .Values.namespace }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
{{- end }}