{{- if or (eq .Values.type "app") (eq .Values.type "worker") }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.appName }}-pdb
  namespace: {{ .Values.namespace }}
spec:
  maxUnavailable: {{ if eq (int .Values.replicaCount) 1 }}0{{ else }}1{{ end }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
{{- end }}